### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by TijsM** [voxeet/voxeet-io-web#33]
There is a typo in the [VideoPresentationService documentation](https://dolby.io/developers/interactivity-apis/client-sdk/reference-javascript/videopresentationservice)

```
VoxeetSDK.filePresentation.on("started", (e: FilePresentation) => {
  /* The video presentation has started. */
})
```

should be

````
const res = VoxeetSDK.videoPresentation.on("started", (e) => {
    /* The video presentation has started. */
  })
```

**Comment by FabienLavocat** [comment]
Thank you for reporting this issue @TijsM. I have created an internal ticket to fix the documentation.
