### ISSUE TITLE
Document the environment variables available on both frontend and backend images

### ISSUE THREAD

**Issue by nladuguie** [voxeet/voxeet-io-web#7]
As a developer, I would like to know which environment variables should I configure on backend and frontend containers to make them work.
This documentation should be written in the readme.me files, and the environment variables available should appear in the Dockerfile with "ENV" instructions : a developer could know how to configure the container quickly just opening the Dockerfile.

**Comment by jfan-dolby** [comment]
Added in the develop branch.

**Comment by Energizz** [comment]
Everything is okay with this ticket @nladuguie ? Can we close it ?
