### ISSUE TITLE
Yarn.lock file references private NPM repository

### ISSUE THREAD

**Issue by nladuguie** [voxeet/voxeet-io-web#8]
During a Docker build from scratch, I faced the following problem :
```
Sending build context to Docker daemon  4.995MB
Step 1/9 : FROM node:12 as build
 ---> b31738bd2a38
Step 2/9 : WORKDIR /app
 ---> Using cache
 ---> cd17ed078c2a
Step 3/9 : COPY . .
 ---> 13a5b22e6d31
Step 4/9 : RUN yarn install
 ---> Running in b59aaf52fc30
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://stg-gke-eu.voxeet.net/nexus/repository/npm-group/react/-/react-16.9.0.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install' returned a non-zero code: 1
```
This caused by the presence of some dependencies in yarn.lock file which are resolved from private repository : for instance "https://stg-gke-eu.voxeet.net/nexus/repository/npm-group/@babel/compat-data/-/compat-data-7.9.6.tgz#3f604c40e420131affe6f2c8052e9a275ae2049b"
"yarn.lock" file should only contain public dependencies and repositories in order that developers can build and run Voxeet.io on their own.

**Comment by jfan-dolby** [comment]
I've removed the yarn.lock file from develop branch.

**Comment by Energizz** [comment]
yarn.lock file has been remove, closing this ticket
